//
//  BrandAccount.swift
//  CareAssistance
//
//  Created by The App Master on 09/11/2023.
//

import Foundation
import RealmSwift

class BrandAccounts: Object, ObjectKeyIdentifiable, Codable {
    @Persisted(primaryKey: true)var totalSize: Int?
    @Persisted var done: Bool?
    @Persisted var records = List<BrandAccount>()
    
}
class BrandAccount: Object, ObjectKeyIdentifiable, Codable  {
    @Persisted(primaryKey: true) var Id: String?
    @Persisted var brandgroupsR: BrandGroups?
    @Persisted var Name: String?
    @Persisted var brandGroupsC: String?
    
    @Persisted var nombreElemento1C: String?
    @Persisted var tipoElemento1C: String?
    @Persisted var atributo11C: String?
    @Persisted var atributo12C: String?
    @Persisted var atributo13C: String?
    @Persisted var atributo14C: String?
    @Persisted var atributo15C: String?
    @Persisted var atributo16C: String?
    @Persisted var atributo17C: String?
    @Persisted var atributo18C: String?
    @Persisted var atributo19C: String?
    @Persisted var Atributo_1_10__c: String?
    @Persisted var Atributo_1_11__c: String?
    @Persisted var Atributo_1_12__c: String?
    @Persisted var Atributo_1_13__c: String?
    @Persisted var Atributo_1_14__c: String?
    @Persisted var Atributo_1_15__c: String?
    @Persisted var Atributo_1_16__c: String?
    @Persisted var parametrosFront1C: String?
    @Persisted var valor11C: String?
    @Persisted var valor12C: String?
    @Persisted var valor13C: String?
    @Persisted var valor14C: String?
    @Persisted var valor15C: String?
    @Persisted var valor16C: String?
    @Persisted var valor17C: String?
    @Persisted var valor18C: String?
    @Persisted var valor19C: String?
    @Persisted var Valor_1_10__c: String?
    @Persisted var Valor_1_11__c: String?
    @Persisted var Valor_1_12__c: String?
    @Persisted var Valor_1_13__c: String?
    @Persisted var Valor_1_14__c: String?
    @Persisted var Valor_1_15__c: String?
    @Persisted var Valor_1_16__c: String?
    
    
    @Persisted var nombreElemento2C: String?
    @Persisted var tipoElemento2C: String?
    @Persisted var atributo21C: String?
    @Persisted var atributo22C: String?
    @Persisted var atributo23C: String?
    @Persisted var atributo24C: String?
    @Persisted var atributo25C: String?
    @Persisted var atributo26C: String?
    @Persisted var atributo27C: String?
    @Persisted var atributo28C: String?
    @Persisted var atributo29C: String?
    @Persisted var atributo210C: String?
    @Persisted var atributo211C: String?
    @Persisted var atributo212C: String?
    @Persisted var atributo213C: String?
    @Persisted var atributo214C: String?
    @Persisted var atributo215C: String?
    @Persisted var atributo216C: String?
    @Persisted var parametrosFront2C: String?
    @Persisted var valor21C: String?
    @Persisted var valor22C: String?
    @Persisted var valor23C: String?
    @Persisted var valor24C: String?
    @Persisted var valor25C: String?
    @Persisted var valor26C: String?
    @Persisted var valor27C: String?
    @Persisted var valor28C: String?
    @Persisted var valor29C: String?
    @Persisted var valor210C: String?
    @Persisted var valor211C: String?
    @Persisted var valor212C: String?
    @Persisted var valor213C: String?
    @Persisted var valor214C: String?
    @Persisted var valor215C: String?
    @Persisted var valor216C: String?
    
    
    @Persisted var nombreElemento3C: String?
    @Persisted var tipoElemento3C: String?
    @Persisted var atributo31C: String?
    @Persisted var atributo32C: String?
    @Persisted var atributo33C: String?
    @Persisted var atributo34C: String?
    @Persisted var atributo35C: String?
    @Persisted var atributo36C: String?
    @Persisted var atributo37C: String?
    @Persisted var atributo38C: String?
    @Persisted var atributo39C: String?
    @Persisted var atributo310C: String?
    @Persisted var atributo311C: String?
    @Persisted var atributo312C: String?
    @Persisted var atributo313C: String?
    @Persisted var atributo314C: String?
    @Persisted var atributo315C: String?
    @Persisted var atributo316C: String?
    @Persisted var parametrosFront3C: String?
    @Persisted var valor31C: String?
    @Persisted var valor32C: String?
    @Persisted var valor33C: String?
    @Persisted var valor34C: String?
    @Persisted var valor35C: String?
    @Persisted var valor36C: String?
    @Persisted var valor37C: String?
    @Persisted var valor38C: String?
    @Persisted var valor39C: String?
    @Persisted var valor310C: String?
    @Persisted var valor311C: String?
    @Persisted var valor312C: String?
    @Persisted var valor313C: String?
    @Persisted var valor314C: String?
    @Persisted var valor315C: String?
    @Persisted var valor316C: String?
    
    @Persisted var nombreElemento4C: String?
    @Persisted var tipoElemento4C: String?
    @Persisted var atributo41C: String?
    @Persisted var atributo42C: String?
    @Persisted var atributo43C: String?
    @Persisted var atributo44C: String?
    @Persisted var atributo45C: String?
    @Persisted var atributo46C: String?
    @Persisted var atributo47C: String?
    @Persisted var atributo48C: String?
    @Persisted var atributo49C: String?
    @Persisted var atributo410C: String?
    @Persisted var atributo411C: String?
    @Persisted var atributo412C: String?
    @Persisted var atributo413C: String?
    @Persisted var atributo414C: String?
    @Persisted var atributo415C: String?
    @Persisted var atributo416C: String?
    @Persisted var parametrosFront4C: String?
    @Persisted var valor41C: String?
    @Persisted var valor42C: String?
    @Persisted var valor43C: String?
    @Persisted var valor44C: String?
    @Persisted var valor45C: String?
    @Persisted var valor46C: String?
    @Persisted var valor47C: String?
    @Persisted var valor48C: String?
    @Persisted var valor49C: String?
    @Persisted var valor410C: String?
    @Persisted var valor411C: String?
    @Persisted var valor412C: String?
    @Persisted var valor413C: String?
    @Persisted var valor414C: String?
    @Persisted var valor415C: String?
    @Persisted var valor416C: String?
    
    @Persisted var nombreElemento5C: String?
    @Persisted var tipoElemento5C: String?
    @Persisted var atributo51C: String?
    @Persisted var atributo52C: String?
    @Persisted var atributo53C: String?
    @Persisted var atributo54C: String?
    @Persisted var atributo55C: String?
    @Persisted var atributo56C: String?
    @Persisted var atributo57C: String?
    @Persisted var atributo58C: String?
    @Persisted var atributo59C: String?
    @Persisted var atributo510C: String?
    @Persisted var atributo511C: String?
    @Persisted var atributo512C: String?
    @Persisted var atributo513C: String?
    @Persisted var atributo514C: String?
    @Persisted var atributo515C: String?
    @Persisted var atributo516C: String?
    @Persisted var parametrosFront5C: String?
    @Persisted var valor51C: String?
    @Persisted var valor52C: String?
    @Persisted var valor53C: String?
    @Persisted var valor54C: String?
    @Persisted var valor55C: String?
    @Persisted var valor56C: String?
    @Persisted var valor57C: String?
    @Persisted var valor58C: String?
    @Persisted var valor59C: String?
    @Persisted var valor510C: String?
    @Persisted var valor511C: String?
    @Persisted var valor512C: String?
    @Persisted var valor513C: String?
    @Persisted var valor514C: String?
    @Persisted var valor515C: String?
    @Persisted var valor516C: String?
    
    @Persisted var nombreElemento6C: String?
    @Persisted var tipoElemento6C: String?
    @Persisted var atributo61C: String?
    @Persisted var atributo62C: String?
    @Persisted var atributo63C: String?
    @Persisted var atributo64C: String?
    @Persisted var atributo65C: String?
    @Persisted var atributo66C: String?
    @Persisted var parametrosFront6C: String?
    @Persisted var valor61C: String?
    @Persisted var valor62C: String?
    @Persisted var valor63C: String?
    @Persisted var valor64C: String?
    @Persisted var valor65C: String?
    @Persisted var valor66C: String?
    @Persisted var valor67C: String?
    @Persisted var valor68C: String?
    @Persisted var valor69C: String?
    @Persisted var valor610C: String?
    @Persisted var valor611C: String?
    @Persisted var valor612C: String?
    @Persisted var valor613C: String?
    @Persisted var valor614C: String?
    @Persisted var valor615C: String?
    @Persisted var valor616C: String?
    
    @Persisted var nombreElemento7C: String?
    @Persisted var tipoElemento7C: String?
    @Persisted var atributo71C: String?
    @Persisted var atributo72C: String?
    @Persisted var atributo73C: String?
    @Persisted var atributo74C: String?
    @Persisted var atributo75C: String?
    @Persisted var atributo76C: String?
    @Persisted var parametrosFront7C: String?
    @Persisted var valor71C: String?
    @Persisted var valor72C: String?
    @Persisted var valor73C: String?
    @Persisted var valor74C: String?
    @Persisted var valor75C: String?
    @Persisted var valor76C: String?
    @Persisted var valor77C: String?
    @Persisted var valor78C: String?
    @Persisted var valor79C: String?
    @Persisted var valor710C: String?
    @Persisted var valor711C: String?
    @Persisted var valor712C: String?
    @Persisted var valor713C: String?
    @Persisted var valor714C: String?
    @Persisted var valor715C: String?
    @Persisted var valor716C: String?
    
    @Persisted var nombreElemento8C: String?
    @Persisted var tipoElemento8C: String?
    @Persisted var atributo81C: String?
    @Persisted var atributo82C: String?
    @Persisted var atributo83C: String?
    @Persisted var atributo84C: String?
    @Persisted var atributo85C: String?
    @Persisted var atributo86C: String?
    @Persisted var parametrosFront8C: String?
    @Persisted var valor81C: String?
    @Persisted var valor82C: String?
    @Persisted var valor83C: String?
    @Persisted var valor84C: String?
    @Persisted var valor85C: String?
    @Persisted var valor86C: String?
    @Persisted var valor87C: String?
    @Persisted var valor88C: String?
    @Persisted var valor89C: String?
    @Persisted var valor810C: String?
    @Persisted var valor811C: String?
    @Persisted var valor812C: String?
    @Persisted var valor813C: String?
    @Persisted var valor814C: String?
    @Persisted var valor815C: String?
    @Persisted var valor816C: String?
    
    @Persisted var nombreElemento9C: String?
    @Persisted var tipoElemento9C: String?
    @Persisted var atributo91C: String?
    @Persisted var atributo92C: String?
    @Persisted var atributo93C: String?
    @Persisted var atributo94C: String?
    @Persisted var atributo95C: String?
    @Persisted var atributo96C: String?
    @Persisted var atributo97C: String?
    @Persisted var atributo98C: String?
    @Persisted var atributo99C: String?
    @Persisted var atributo910C: String?
    @Persisted var atributo911C: String?
    @Persisted var atributo912C: String?
    @Persisted var atributo913C: String?
    @Persisted var atributo914C: String?
    @Persisted var atributo915C: String?
    @Persisted var atributo916C: String?
    @Persisted var parametrosFront9C: String?
    @Persisted var valor91C: String?
    @Persisted var valor92C: String?
    @Persisted var valor93C: String?
    @Persisted var valor94C: String?
    @Persisted var valor95C: String?
    @Persisted var valor96C: String?
    @Persisted var valor97C: String?
    @Persisted var valor98C: String?
    @Persisted var valor99C: String?
    @Persisted var valor910C: String?
    @Persisted var valor911C: String?
    @Persisted var valor912C: String?
    @Persisted var valor913C: String?
    @Persisted var valor914C: String?
    @Persisted var valor915C: String?
    @Persisted var valor916C: String?
    
    
    @Persisted var nombreElemento10C: String?
    @Persisted var tipoElemento10C: String?
    @Persisted var atributo101C: String?
    @Persisted var atributo102C: String?
    @Persisted var atributo103C: String?
    @Persisted var atributo104C: String?
    @Persisted var atributo105C: String?
    @Persisted var atributo106C: String?
    @Persisted var parametrosFront10C: String?
    @Persisted var valor101C: String?
    @Persisted var valor102C: String?
    @Persisted var valor103C: String?
    @Persisted var valor104C: String?
    @Persisted var valor105C: String?
    @Persisted var valor106C: String?
    @Persisted var valor107C: String?
    @Persisted var valor108C: String?
    @Persisted var valor109C: String?
    @Persisted var valor1010C: String?
    @Persisted var valor1011C: String?
    @Persisted var valor1012C: String?
    @Persisted var valor1013C: String?
    @Persisted var valor1014C: String?
    @Persisted var valor1015C: String?
    @Persisted var valor1016C: String?
    
    @Persisted var nombreElemento11C: String?
    @Persisted var tipoElemento11C: String?
    @Persisted var atributo111C: String?
    @Persisted var atributo112C: String?
    @Persisted var atributo113C: String?
    @Persisted var atributo114C: String?
    @Persisted var atributo115C: String?
    @Persisted var atributo116C: String?
    @Persisted var parametrosFront11C: String?
    @Persisted var Valor_11_1__c: String?
    @Persisted var Valor_11_2__c: String?
    @Persisted var Valor_11_3__c: String?
    @Persisted var Valor_11_4__c: String?
    @Persisted var Valor_11_5__c: String?
    @Persisted var Valor_11_6__c: String?
    @Persisted var Valor_11_7__c: String?
    @Persisted var Valor_11_8__c: String?
    @Persisted var Valor_11_9__c: String?
    @Persisted var Valor_11_10__c: String?
    @Persisted var Valor_11_11__c: String?
    @Persisted var Valor_11_12__c: String?
    @Persisted var Valor_11_13__c: String?
    @Persisted var Valor_11_14__c: String?
    @Persisted var Valor_11_15__c: String?
    @Persisted var Valor_11_16__c: String?
    
    @Persisted var nombreElemento12C: String?
    @Persisted var tipoElemento12C: String?
    @Persisted var atributo121C: String?
    @Persisted var atributo122C: String?
    @Persisted var atributo123C: String?
    @Persisted var atributo124C: String?
    @Persisted var atributo125C: String?
    @Persisted var atributo126C: String?
    @Persisted var parametrosFront12C: String?
    @Persisted var valor121C: String?
    @Persisted var valor122C: String?
    @Persisted var valor123C: String?
    @Persisted var valor124C: String?
    @Persisted var valor125C: String?
    @Persisted var valor126C: String?
    @Persisted var valor127C: String?
    @Persisted var valor128C: String?
    @Persisted var valor129C: String?
    @Persisted var valor1210C: String?
    @Persisted var valor1211C: String?
    @Persisted var valor1212C: String?
    @Persisted var valor1213C: String?
    @Persisted var valor1214C: String?
    @Persisted var valor1215C: String?
    @Persisted var valor1216C: String?
    
    @Persisted var nombreElemento13C: String?
    @Persisted var tipoElemento13C: String?
    @Persisted var atributo131C: String?
    @Persisted var atributo132C: String?
    @Persisted var atributo133C: String?
    @Persisted var atributo134C: String?
    @Persisted var atributo135C: String?
    @Persisted var atributo136C: String?
    @Persisted var parametrosFront13C: String?
    @Persisted var valor131C: String?
    @Persisted var valor132C: String?
    @Persisted var valor133C: String?
    @Persisted var valor134C: String?
    @Persisted var valor135C: String?
    @Persisted var valor136C: String?
    @Persisted var valor137C: String?
    @Persisted var valor138C: String?
    @Persisted var valor139C: String?
    @Persisted var valor1310C: String?
    @Persisted var valor1311C: String?
    @Persisted var valor1312C: String?
    @Persisted var valor1313C: String?
    @Persisted var valor1314C: String?
    @Persisted var valor1315C: String?
    @Persisted var valor1316C: String?
    enum CodingKeys: String, CodingKey {
        case Id
        case brandgroupsR = "Brand_Groups__r"
        case Name
        case brandGroupsC = "Brand_Groups__c"
        
        case nombreElemento1C = "Nombre_Elemento_1__c"
        case tipoElemento1C = "Tipo_Elemento_1__c"
        case atributo11C = "Atributo_1_1__c"
        case atributo12C = "Atributo_1_2__c"
        case atributo13C = "Atributo_1_3__c"
        case atributo14C = "Atributo_1_4__c"
        case atributo15C = "Atributo_1_5__c"
        case atributo16C = "Atributo_1_6__c"
        case atributo17C = "Atributo_1_7__c"
        case atributo18C = "Atributo_1_8__c"
        case atributo19C = "Atributo_1_9__c"
        case Atributo_1_10__c = "Atributo_1_10__c"
        case Atributo_1_11__c = "Atributo_1_11__c"
        case Atributo_1_12__c = "Atributo_1_12__c"
        case Atributo_1_13__c = "Atributo_1_13__c"
        case Atributo_1_14__c = "Atributo_1_14__c"
        case Atributo_1_15__c = "Atributo_1_15__c"
        case Atributo_1_16__c = "Atributo_1_16__c"
        case parametrosFront1C = "Parametros_Front_1__c"
        case valor11C = "Valor_1_1__c"
        case valor12C = "Valor_1_2__c"
        case valor13C = "Valor_1_3__c"
        case valor14C = "Valor_1_4__c"
        case valor15C = "Valor_1_5__c"
        case valor16C = "Valor_1_6__c"
        case valor17C = "Valor_1_7__c"
        case valor18C = "Valor_1_8__c"
        case valor19C = "Valor_1_9__c"
        case Valor_1_10__c = "Valor_1_10__c"
        case Valor_1_11__c = "Valor_1_11__c"
        case Valor_1_12__c = "Valor_1_12__c"
        case Valor_1_13__c = "Valor_1_13__c"
        case Valor_1_14__c = "Valor_1_14__c"
        case Valor_1_15__c = "Valor_1_15__c"
        case Valor_1_16__c = "Valor_1_16__c"

        case nombreElemento2C = "Nombre_Elemento_2__c"
        case tipoElemento2C = "Tipo_Elemento_2__c"
        case atributo21C = "Atributo_2_1__c"
        case atributo22C = "Atributo_2_2__c"
        case atributo23C = "Atributo_2_3__c"
        case atributo24C = "Atributo_2_4__c"
        case atributo25C = "Atributo_2_5__c"
        case atributo26C = "Atributo_2_6__c"
        case atributo27C = "Atributo_2_7__c"
        case atributo28C = "Atributo_2_8__c"
        case atributo29C = "Atributo_2_9__c"
        case atributo210C = "Atributo_2_10__c"
        case atributo211C = "Atributo_2_11__c"
        case atributo212C = "Atributo_2_12__c"
        case atributo213C = "Atributo_2_13__c"
        case atributo214C = "Atributo_2_14__c"
        case atributo215C = "Atributo_2_15__c"
        case atributo216C = "Atributo_2_16__c"
        case parametrosFront2C = "Parametros_Front_2__c"
        case valor21C = "Valor_2_1__c"
        case valor22C = "Valor_2_2__c"
        case valor23C = "Valor_2_3__c"
        case valor24C = "Valor_2_4__c"
        case valor25C = "Valor_2_5__c"
        case valor26C = "Valor_2_6__c"
        case valor27C = "Valor_2_7__c"
        case valor28C = "Valor_2_8__c"
        case valor29C = "Valor_2_9__c"
        case valor210C = "Valor_2_10__c"
        case valor211C = "Valor_2_11__c"
        case valor212C = "Valor_2_12__c"
        case valor213C = "Valor_2_13__c"
        case valor214C = "Valor_2_14__c"
        case valor215C = "Valor_2_15__c"
        case valor216C = "Valor_2_16__c"
        
        case nombreElemento3C = "Nombre_Elemento_3__c"
        case tipoElemento3C = "Tipo_Elemento_3__c"
        case atributo31C = "Atributo_3_1__c"
        case atributo32C = "Atributo_3_2__c"
        case atributo33C = "Atributo_3_3__c"
        case atributo34C = "Atributo_3_4__c"
        case atributo35C = "Atributo_3_5__c"
        case atributo36C = "Atributo_3_6__c"
        case atributo37C = "Atributo_3_7__c"
        case atributo38C = "Atributo_3_8__c"
        case atributo39C = "Atributo_3_9__c"
        case atributo310C = "Atributo_3_10__c"
        case atributo311C = "Atributo_3_11__c"
        case atributo312C = "Atributo_3_12__c"
        case atributo313C = "Atributo_3_13__c"
        case atributo314C = "Atributo_3_14__c"
        case atributo315C = "Atributo_3_15__c"
        case atributo316C = "Atributo_3_16__c"
        case parametrosFront3C = "Parametros_Front_3__c"
        case valor31C = "Valor_3_1__c"
        case valor32C = "Valor_3_2__c"
        case valor33C = "Valor_3_3__c"
        case valor34C = "Valor_3_4__c"
        case valor35C = "Valor_3_5__c"
        case valor36C = "Valor_3_6__c"
        case valor37C = "Valor_3_7__c"
        case valor38C = "Valor_3_8__c"
        case valor39C = "Valor_3_9__c"
        case valor310C = "Valor_3_10__c"
        case valor311C = "Valor_3_11__c"
        case valor312C = "Valor_3_12__c"
        case valor313C = "Valor_3_13__c"
        case valor314C = "Valor_3_14__c"
        case valor315C = "Valor_3_15__c"
        case valor316C = "Valor_3_16__c"
        
        case nombreElemento4C = "Nombre_Elemento_4__c"
        case tipoElemento4C = "Tipo_Elemento_4__c"
        case atributo41C = "Atributo_4_1__c"
        case atributo42C = "Atributo_4_2__c"
        case atributo43C = "Atributo_4_3__c"
        case atributo44C = "Atributo_4_4__c"
        case atributo45C = "Atributo_4_5__c"
        case atributo46C = "Atributo_4_6__c"
        case atributo47C = "Atributo_4_7__c"
        case atributo48C = "Atributo_4_8__c"
        case atributo49C = "Atributo_4_9__c"
        case atributo410C = "Atributo_4_10__c"
        case atributo411C = "Atributo_4_11__c"
        case atributo412C = "Atributo_4_12__c"
        case atributo413C = "Atributo_4_13__c"
        case atributo414C = "Atributo_4_14__c"
        case atributo415C = "Atributo_4_15__c"
        case atributo416C = "Atributo_4_16__c"
        case parametrosFront4C = "Parametros_Front_4__c"
        case valor41C = "Valor_4_1__c"
        case valor42C = "Valor_4_2__c"
        case valor43C = "Valor_4_3__c"
        case valor44C = "Valor_4_4__c"
        case valor45C = "Valor_4_5__c"
        case valor46C = "Valor_4_6__c"
        case valor47C = "Valor_4_7__c"
        case valor48C = "Valor_4_8__c"
        case valor49C = "Valor_4_9__c"
        case valor410C = "Valor_4_10__c"
        case valor411C = "Valor_4_11__c"
        case valor412C = "Valor_4_12__c"
        case valor413C = "Valor_4_13__c"
        case valor414C = "Valor_4_14__c"
        case valor415C = "Valor_4_15__c"
        case valor416C = "Valor_4_16__c"
        
        case nombreElemento5C = "Nombre_Elemento_5__c"
        case tipoElemento5C = "Tipo_Elemento_5__c"
        case atributo51C = "Atributo_5_1__c"
        case atributo52C = "Atributo_5_2__c"
        case atributo53C = "Atributo_5_3__c"
        case atributo54C = "Atributo_5_4__c"
        case atributo55C = "Atributo_5_5__c"
        case atributo56C = "Atributo_5_6__c"
        case atributo57C = "Atributo_5_7__c"
        case atributo58C = "Atributo_5_8__c"
        case atributo59C = "Atributo_5_9__c"
        case atributo510C = "Atributo_5_10__c"
        case atributo511C = "Atributo_5_11__c"
        case atributo512C = "Atributo_5_12__c"
        case atributo513C = "Atributo_5_13__c"
        case atributo514C = "Atributo_5_14__c"
        case atributo515C = "Atributo_5_15__c"
        case atributo516C = "Atributo_5_16__c"
        case parametrosFront5C = "Parametros_Front_5__c"
        case valor51C = "Valor_5_1__c"
        case valor52C = "Valor_5_2__c"
        case valor53C = "Valor_5_3__c"
        case valor54C = "Valor_5_4__c"
        case valor55C = "Valor_5_5__c"
        case valor56C = "Valor_5_6__c"
        case valor57C = "Valor_5_7__c"
        case valor58C = "Valor_5_8__c"
        case valor59C = "Valor_5_9__c"
        case valor510C = "Valor_5_10__c"
        case valor511C = "Valor_5_11__c"
        case valor512C = "Valor_5_12__c"
        case valor513C = "Valor_5_13__c"
        case valor514C = "Valor_5_14__c"
        case valor515C = "Valor_5_15__c"
        case valor516C = "Valor_5_16__c"
        
        case nombreElemento6C = "Nombre_Elemento_6__c"
        case tipoElemento6C = "Tipo_Elemento_6__c"
        case atributo61C = "Atributo_6_1__c"
        case atributo62C = "Atributo_6_2__c"
        case atributo63C = "Atributo_6_3__c"
        case atributo64C = "Atributo_6_4__c"
        case atributo65C = "Atributo_6_5__c"
        case atributo66C = "Atributo_6_6__c"
        case parametrosFront6C = "Parametros_Front_6__c"
        case valor61C = "Valor_6_1__c"
        case valor62C = "Valor_6_2__c"
        case valor63C = "Valor_6_3__c"
        case valor64C = "Valor_6_4__c"
        case valor65C = "Valor_6_5__c"
        case valor66C = "Valor_6_6__c"
        case valor67C = "Valor_6_7__c"
        case valor68C = "Valor_6_8__c"
        case valor69C = "Valor_6_9__c"
        case valor610C = "Valor_6_10__c"
        case valor611C = "Valor_6_11__c"
        case valor612C = "Valor_6_12__c"
        case valor613C = "Valor_6_13__c"
        case valor614C = "Valor_6_14__c"
        case valor615C = "Valor_6_15__c"
        case valor616C = "Valor_6_16__c"
        
        case nombreElemento7C = "Nombre_Elemento_7__c"
        case tipoElemento7C = "Tipo_Elemento_7__c"
        case atributo71C = "Atributo_7_1__c"
        case atributo72C = "Atributo_7_2__c"
        case atributo73C = "Atributo_7_3__c"
        case atributo74C = "Atributo_7_4__c"
        case atributo75C = "Atributo_7_5__c"
        case atributo76C = "Atributo_7_6__c"
        case parametrosFront7C = "Parametros_Front_7__c"
        case valor71C = "Valor_7_1__c"
        case valor72C = "Valor_7_2__c"
        case valor73C = "Valor_7_3__c"
        case valor74C = "Valor_7_4__c"
        case valor75C = "Valor_7_5__c"
        case valor76C = "Valor_7_6__c"
        case valor77C = "Valor_7_7__c"
        case valor78C = "Valor_7_8__c"
        case valor79C = "Valor_7_9__c"
        case valor710C = "Valor_7_10__c"
        case valor711C = "Valor_7_11__c"
        case valor712C = "Valor_7_12__c"
        case valor713C = "Valor_7_13__c"
        case valor714C = "Valor_7_14__c"
        case valor715C = "Valor_7_15__c"
        case valor716C = "Valor_7_16__c"
        
        case nombreElemento8C = "Nombre_Elemento_8__c"
        case tipoElemento8C = "Tipo_Elemento_8__c"
        case atributo81C = "Atributo_8_1__c"
        case atributo82C = "Atributo_8_2__c"
        case atributo83C = "Atributo_8_3__c"
        case atributo84C = "Atributo_8_4__c"
        case atributo85C = "Atributo_8_5__c"
        case atributo86C = "Atributo_8_6__c"
        case parametrosFront8C = "Parametros_Front_8__c"
        case valor81C = "Valor_8_1__c"
        case valor82C = "Valor_8_2__c"
        case valor83C = "Valor_8_3__c"
        case valor84C = "Valor_8_4__c"
        case valor85C = "Valor_8_5__c"
        case valor86C = "Valor_8_6__c"
        case valor87C = "Valor_8_7__c"
        case valor88C = "Valor_8_8__c"
        case valor89C = "Valor_8_9__c"
        case valor810C = "Valor_8_10__c"
        case valor811C = "Valor_8_11__c"
        case valor812C = "Valor_8_12__c"
        case valor813C = "Valor_8_13__c"
        case valor814C = "Valor_8_14__c"
        case valor815C = "Valor_8_15__c"
        case valor816C = "Valor_8_16__c"
        
        case nombreElemento9C = "Nombre_Elemento_9__c"
        case tipoElemento9C = "Tipo_Elemento_9__c"
        case atributo91C = "Atributo_9_1__c"
        case atributo92C = "Atributo_9_2__c"
        case atributo93C = "Atributo_9_3__c"
        case atributo94C = "Atributo_9_4__c"
        case atributo95C = "Atributo_9_5__c"
        case atributo96C = "Atributo_9_6__c"
        case atributo97C = "Atributo_9_7__c"
        case atributo98C = "Atributo_9_8__c"
        case atributo99C = "Atributo_9_9__c"
        case atributo910C = "Atributo_9_10__c"
        case atributo911C = "Atributo_9_11__c"
        case atributo912C = "Atributo_9_12__c"
        case atributo913C = "Atributo_9_13__c"
        case atributo914C = "Atributo_9_14__c"
        case atributo915C = "Atributo_9_15__c"
        case atributo916C = "Atributo_9_16__c"
        case parametrosFront9C = "Parametros_Front_9__c"
        case valor91C = "Valor_9_1__c"
        case valor92C = "Valor_9_2__c"
        case valor93C = "Valor_9_3__c"
        case valor94C = "Valor_9_4__c"
        case valor95C = "Valor_9_5__c"
        case valor96C = "Valor_9_6__c"
        case valor97C = "Valor_9_7__c"
        case valor98C = "Valor_9_8__c"
        case valor99C = "Valor_9_9__c"
        case valor910C = "Valor_9_10__c"
        case valor911C = "Valor_9_11__c"
        case valor912C = "Valor_9_12__c"
        case valor913C = "Valor_9_13__c"
        case valor914C = "Valor_9_14__c"
        case valor915C = "Valor_9_15__c"
        case valor916C = "Valor_9_16__c"
        
        case nombreElemento10C = "Nombre_Elemento_10__c"
        case tipoElemento10C = "Tipo_Elemento_10__c"
        case atributo101C = "Atributo_10_1__c"
        case atributo102C = "Atributo_10_2__c"
        case atributo103C = "Atributo_10_3__c"
        case atributo104C = "Atributo_10_4__c"
        case atributo105C = "Atributo_10_5__c"
        case atributo106C = "Atributo_10_6__c"
        case parametrosFront10C = "Parametros_Front_10__c"
        case valor101C = "Valor_10_1__c"
        case valor102C = "Valor_10_2__c"
        case valor103C = "Valor_10_3__c"
        case valor104C = "Valor_10_4__c"
        case valor105C = "Valor_10_5__c"
        case valor106C = "Valor_10_6__c"
        case valor107C = "Valor_10_7__c"
        case valor108C = "Valor_10_8__c"
        case valor109C = "Valor_10_9__c"
        case valor1010C = "Valor_10_10__c"
        case valor1011C = "Valor_10_11__c"
        case valor1012C = "Valor_10_12__c"
        case valor1013C = "Valor_10_13__c"
        case valor1014C = "Valor_10_14__c"
        case valor1015C = "Valor_10_15__c"
        case valor1016C = "Valor_10_16__c"
        
        case nombreElemento11C = "Nombre_Elemento_11__c"
        case tipoElemento11C = "Tipo_Elemento_11__c"
        case atributo111C = "Atributo_11_1__c"
        case atributo112C = "Atributo_11_2__c"
        case atributo113C = "Atributo_11_3__c"
        case atributo114C = "Atributo_11_4__c"
        case atributo115C = "Atributo_11_5__c"
        case atributo116C = "Atributo_11_6__c"
        case parametrosFront11C = "Parametros_Front_11__c"
        case Valor_11_1__c = "Valor_11_1__c"
        case Valor_11_2__c = "Valor_11_2__c"
        case Valor_11_3__c = "Valor_11_3__c"
        case Valor_11_4__c = "Valor_11_4__c"
        case Valor_11_5__c = "Valor_11_5__c"
        case Valor_11_6__c = "Valor_11_6__c"
        case Valor_11_7__c = "Valor_11_7__c"
        case Valor_11_8__c = "Valor_11_8__c"
        case Valor_11_9__c = "Valor_11_9__c"
        case Valor_11_10__c = "Valor_11_10__c"
        case Valor_11_11__c = "Valor_11_11__c"
        case Valor_11_12__c = "Valor_11_12__c"
        case Valor_11_13__c = "Valor_11_13__c"
        case Valor_11_14__c = "Valor_11_14__c"
        case Valor_11_15__c = "Valor_11_15__c"
        case Valor_11_16__c = "Valor_11_16__c"
        
        case nombreElemento12C = "Nombre_Elemento_12__c"
        case tipoElemento12C = "Tipo_Elemento_12__c"
        case atributo121C = "Atributo_12_1__c"
        case atributo122C = "Atributo_12_2__c"
        case atributo123C = "Atributo_12_3__c"
        case atributo124C = "Atributo_12_4__c"
        case atributo125C = "Atributo_12_5__c"
        case atributo126C = "Atributo_12_6__c"
        case parametrosFront12C = "Parametros_Front_12__c"
        case valor121C = "Valor_12_1__c"
        case valor122C = "Valor_12_2__c"
        case valor123C = "Valor_12_3__c"
        case valor124C = "Valor_12_4__c"
        case valor125C = "Valor_12_5__c"
        case valor126C = "Valor_12_6__c"
        case valor127C = "Valor_12_7__c"
        case valor128C = "Valor_12_8__c"
        case valor129C = "Valor_12_9__c"
        case valor1210C = "Valor_12_10__c"
        case valor1211C = "Valor_12_11__c"
        case valor1212C = "Valor_12_12__c"
        case valor1213C = "Valor_12_13__c"
        case valor1214C = "Valor_12_14__c"
        case valor1215C = "Valor_12_15__c"
        case valor1216C = "Valor_12_16__c"
        
        case nombreElemento13C = "Nombre_Elemento_13__c"
        case tipoElemento13C = "Tipo_Elemento_13__c"
        case atributo131C = "Atributo_13_1__c"
        case atributo132C = "Atributo_13_2__c"
        case atributo133C = "Atributo_13_3__c"
        case atributo134C = "Atributo_13_4__c"
        case atributo135C = "Atributo_13_5__c"
        case atributo136C = "Atributo_13_6__c"
        case parametrosFront13C = "Parametros_Front_13__c"
        case valor131C = "Valor_13_1__c"
        case valor132C = "Valor_13_2__c"
        case valor133C = "Valor_13_3__c"
        case valor134C = "Valor_13_4__c"
        case valor135C = "Valor_13_5__c"
        case valor136C = "Valor_13_6__c"
        case valor137C = "Valor_13_7__c"
        case valor138C = "Valor_13_8__c"
        case valor139C = "Valor_13_9__c"
        case valor1310C = "Valor_13_10__c"
        case valor1311C = "Valor_13_11__c"
        case valor1312C = "Valor_13_12__c"
        case valor1313C = "Valor_13_13__c"
        case valor1314C = "Valor_13_14__c"
        case valor1315C = "Valor_13_15__c"
        case valor1316C = "Valor_13_16__c"
        
    }
}

class BrandGroups: Object, Codable {
    @Persisted var Name: String?
    @Persisted var convenioC: String?
    @Persisted var empresaC: String?
    @Persisted var campanaC: String?
    @Persisted var polizaC: String?
    
    enum CodingKeys: String, CodingKey {
        case Name
        case convenioC = "Convenio__c"
        case empresaC = "Empresa__c"
        case campanaC = "Campana__c"
        case polizaC = "Poliza__c"
    }
}

extension BrandAccount {
    func getBrandValue(section: Int, field: Int) -> String? {
        var propertyName = ""

        if section == 11 {
            propertyName = "Valor_11_\(field)__c"
        } else if section == 1 && field >= 10 {
            propertyName = "Valor_1_\(field)__c"
        } else {
            propertyName = "valor\(section)\(field)C"
        }

        // ✅ Usa value(forKey:) en lugar de Mirror
        if let object = self as? NSObject {
            if let value = object.value(forKey: propertyName) as? String {
                return value
            }
        }

        return nil
    }
}
